micronaut:
  application:
    name: mnOciFinal
datasources:
  default:
    url: jdbc:oracle:thin:@barnevents_low?TNS_ADMIN=/wallet
    connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
    username: testuser
    schema-generate: CREATE_DROP
    dialect: ORACLE
    minPoolSize: 1
    maxPoolSize: 10
jpa.default.properties.hibernate.hbm2ddl.auto: update
codes:
  recursive:
    test: 'This is localhost'